### ISSUE TITLE
Use link to Enterprise API specs

### ISSUE THREAD

**Issue by zhill** [twilio-labs/twilio-anchore#1]
Hi! Thanks for making this, and very exciting to see it public!

I noticed the link to Engine and I'd like to suggest a link the Enterprise API specs (which include engine) so folks can see the full set: https://docs.anchore.com/current/docs/using/api_usage/

I'm happy to open a PR for that if it is ok. Thanks again!

**Comment by juanjoselmm** [comment]
Thanks a lot for the suggestion.
I have added the link in the README file.

**Comment by zhill** [comment]
Thanks! Much appreciated!
